import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "AgriMitra🌿",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Navbar is now fixed at the top */}
        <Navbar />
        <main className="pt-20">{children}</main>
      </body>
    </html>
  );
}
